version: '2'
services:
    db:
        image: mysql:5.7
        ports:
            - "3306:3306"
        volumes:
            - "./bitcoinWallet/db/mysql_init:/docker-entrypoint-initdb.d"
            - "./bitcoinWallet/db/mysql_data:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: mysql

    web:
        image: node:10.7.0
        build: 
            context: ./
            dockerfile: dockerfile
        tty: true
        links: 
            - db
        ports: 
            - 80:3000
        